---
version: 0.1.15
slug: tasmota_ccc
name: Tasmota proxy and update 
panel_icon: mdi:home-automation
panel_title: Tasmota proxy
description: Access and update your Tasmota devices through Home Assistant
url: https://github.com/lmagyar/homeassistant-addon-tasmota-ccc
image: ghcr.io/lmagyar/{arch}-addon-tasmota-ccc
codenotary: lmagyar1973@gmail.com
arch:
  - aarch64
  - amd64
  - armv7
map:
  - share:rw
init: false
homeassistant_api: true
host_network: true
ingress: true
ingress_port: 0
